FROM ubuntu:18.04

RUN apt-get update \
    && apt-get install -y openjdk-8-jdk \
    && apt-get install -y wget

RUN wget https://github.com/RichardAGoldstein/HaROLD/releases/download/v1.0/harold-1.0.jar